import * as THREE from 'three';
import {packedReceiverGLSL,type ReceiverBridge} from '../ocean/receiver-bridge.ts';
export function inspectGeometryRays(renderer:THREE.WebGLRenderer,bridge:ReceiverBridge,center:THREE.Vector3){
  const rays=bridge.geometry.inspectionRays(center,4);if(!rays.length)throw new Error('No actual receiver triangles for inspection');
  const saved={target:renderer.getRenderTarget(),viewport:renderer.getViewport(new THREE.Vector4()),scissor:renderer.getScissor(new THREE.Vector4()),test:renderer.getScissorTest(),color:renderer.getClearColor(new THREE.Color()),alpha:renderer.getClearAlpha(),auto:renderer.autoClear,tone:renderer.toneMapping,space:renderer.outputColorSpace};
  const target=new THREE.WebGLRenderTarget(4,1,{type:THREE.FloatType,depthBuffer:false}),geometry=new THREE.PlaneGeometry(2,2);
  const material=new THREE.ShaderMaterial({depthTest:false,depthWrite:false,toneMapped:false,uniforms:{...bridge.uniforms,origins:{value:rays.map(r=>r.origin)},directions:{value:rays.map(r=>r.direction)},limits:{value:rays.map(r=>r.maxDistance)},mode:{value:0}},vertexShader:'void main(){gl_Position=vec4(position,1.);}',fragmentShader:`${packedReceiverGLSL}\nuniform vec3 origins[4],directions[4];uniform float limits[4];uniform int mode;void main(){int index=int(gl_FragCoord.x);vec3 p,n,c;vec2 uv;int m;bool hit=traceReceiver(origins[index],directions[index],limits[index],p,n,uv,m,c);if(!hit){gl_FragColor=vec4(0);return;}if(mode==0)gl_FragColor=vec4(p,1.);else if(mode==1)gl_FragColor=vec4(n,float(m));else gl_FragColor=vec4(uv,c.r,1.);}`});
  const scene=new THREE.Scene();scene.add(new THREE.Mesh(geometry,material));const camera=new THREE.Camera(),pixels=new Float32Array(16),values:number[][][]=[[],[],[],[]];
  try{
    renderer.autoClear=true;renderer.setClearColor(0,0);renderer.setScissorTest(false);renderer.toneMapping=THREE.NoToneMapping;renderer.outputColorSpace=THREE.LinearSRGBColorSpace;renderer.setRenderTarget(target);renderer.setViewport(0,0,4,1);
    for(let mode=0;mode<3;mode++){material.uniforms.mode.value=mode;renderer.render(scene,camera);renderer.readRenderTargetPixels(target,0,0,4,1,pixels);for(let i=0;i<rays.length;i++)values[i].push(Array.from(pixels.slice(i*4,i*4+4)));}
    return {rays:rays.map((ray,i)=>{const cpu=bridge.geometry.traceCPU(ray.origin,ray.direction,ray.maxDistance);return {source:ray.source,origin:ray.origin.toArray(),direction:ray.direction.toArray(),maxDistance:ray.maxDistance,gpu:values[i],cpu:cpu?{point:cpu.point.toArray(),normal:cpu.normal.toArray(),uv:cpu.uv.toArray(),materialId:cpu.materialId,distance:cpu.distance}:null};}),scope:'Actual selected triangle targets and current packed GPU data, independent CPU triangle intersection with AABB pruning. Four rays only, not all-scene coverage or Human proof'};
  }finally{renderer.setRenderTarget(saved.target);renderer.setViewport(saved.viewport);renderer.setScissor(saved.scissor);renderer.setScissorTest(saved.test);renderer.setClearColor(saved.color,saved.alpha);renderer.autoClear=saved.auto;renderer.toneMapping=saved.tone;renderer.outputColorSpace=saved.space;target.dispose();geometry.dispose();material.dispose();}
}
