import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {ReceiverBridge,packReceiverMaterialParameters,RECEIVER_PARAM_TEXELS,receiverMaterialGLSL} from '../src/ocean/receiver-bridge.ts';
import {receiverTraceGLSL} from '../src/ocean/geometry-receivers-glsl.ts';
const installCanvas=()=>{Object.assign(globalThis,{document:{createElement:()=>({width:0,height:0,getContext:()=>({clearRect(){},drawImage(){},putImageData(){},createImageData(w:number,h:number){return {data:new Uint8ClampedArray(w*h*4)};},getImageData(){return {data:new Uint8ClampedArray(512*512*4).fill(128)};}})})}});};
test('map gamma metadata preserves raw normals and independent native UV/wrap/flip',()=>{
 const albedo=new THREE.Texture({width:1,height:1}),normal=new THREE.Texture({width:1,height:1});albedo.colorSpace=THREE.SRGBColorSpace;normal.colorSpace=THREE.SRGBColorSpace;normal.repeat.set(2,3);normal.offset.set(.2,.4);normal.wrapS=THREE.MirroredRepeatWrapping;normal.flipY=true;
 const m=new THREE.MeshStandardMaterial({map:albedo,normalMap:normal});m.normalScale.set(.6,-.8);const p=packReceiverMaterialParameters([m],new Map([[albedo,0],[normal,1]]));
 assert.equal(p[16],0);assert.equal(p[17],1);assert.equal(p[28],1);assert.equal(p[29],1);assert.equal(p[30],1);assert.equal(p[32],2);assert.equal(p[35],2);assert.equal(p[37],3);assert.ok(Math.abs(p[12]-.6)<1e-6);
 assert.match(receiverMaterialGLSL,/receiverMap\(id,1,uv,vec4\(.5,.5,1,1\),false\)/);assert.match(receiverMaterialGLSL,/colour&&f.y/);
});
test('unsupported UV and object normal encodings fail explicitly',()=>{const map=new THREE.Texture();map.channel=1;const m=new THREE.MeshStandardMaterial({map});assert.throws(()=>packReceiverMaterialParameters([m],new Map([[map,0]])),/UV channel 1/);m.map=null;m.normalMap=map;map.channel=0;m.normalMapType=THREE.ObjectSpaceNormalMap;assert.throws(()=>packReceiverMaterialParameters([m],new Map()),/object-space/);});
test('scalar wetness and mixed extra material updates preserve static geometry and atlas epochs',()=>{
 installCanvas();const scene=new THREE.Scene(),m=new THREE.MeshStandardMaterial({roughness:.8});scene.add(new THREE.Mesh(new THREE.BoxGeometry(),m));const extra=new THREE.MeshStandardMaterial({color:'red'}),sand=new THREE.Texture({width:1,height:1});const bridge=new ReceiverBridge(scene,()=>true,4096,64,sand,{extraMaterials:()=>[extra]});assert.equal(bridge.diagnostics.available,true,bridge.diagnostics.reason);
 const staticTexture=bridge.uniforms.receiverStatic.value,staticVersion=staticTexture.version,rebuilds=bridge.diagnostics.rebuilds,atlas=bridge.diagnostics.atlasRebuilds,updates=bridge.diagnostics.parameterUpdates;
 m.roughness=.15;m.color.set('blue');m.emissive.set('green');extra.metalness=.7;assert.equal(bridge.sync(),true);assert.equal(bridge.uniforms.receiverStatic.value,staticTexture);assert.equal(staticTexture.version,staticVersion);assert.equal(bridge.diagnostics.rebuilds,rebuilds);assert.equal(bridge.diagnostics.atlasRebuilds,atlas);assert.equal(bridge.diagnostics.parameterUpdates,updates+1);assert.equal(bridge.uniforms.receiverExtraMaterialBase.value,1);assert.equal(bridge.uniforms.receiverBedMaterial.value,2);
 const texture=bridge.uniforms.receiverDynamic.value as THREE.DataTexture,p=texture.image.data as Float32Array,offset=Number(bridge.uniforms.receiverMaterialOffset.value)*4;assert.ok(Math.abs(p[offset+3]-.15)<1e-6);assert.ok(Math.abs(p[offset+RECEIVER_PARAM_TEXELS*4] -1)<1e-6);bridge.dispose();assert.equal(sand.version,0);
});
test('triangle basis handles nonuniform reflected transforms without derivatives',()=>{
 const e1=new THREE.Vector3(1,0,0),e2=new THREE.Vector3(0,1,0),world=new THREE.Matrix3().set(-2,0,0,0,3,0,0,0,.5),n=new THREE.Vector3(0,0,1),t=e1.applyMatrix3(world).normalize(),bt=e2.applyMatrix3(world).normalize(),b=new THREE.Vector3().crossVectors(n,t);b.multiplyScalar(Math.sign(b.dot(bt)));assert.deepEqual(t.toArray(),[-1,0,0]);assert.ok(b.distanceTo(new THREE.Vector3(0,1,0))<1e-9);assert.equal(t.dot(n),0);assert.equal(b.dot(n),0);assert.match(receiverTraceGLSL,/worldMatrix=inverse\(mat3\(inverseWorld\)\)/);assert.match(receiverTraceGLSL,/sign\(dot\(cross\(normalWorld,tangentWorld\),bt\)\)/);assert.doesNotMatch(receiverTraceGLSL,/dFdx|dFdy/);
});
test('texture epoch refresh is independent of geometry; GPU budget fails without dropping maps',()=>{
 installCanvas();const scene=new THREE.Scene(),map=new THREE.Texture({width:1,height:1}),normal=new THREE.Texture({width:1,height:1}),sand=new THREE.Texture({width:1,height:1}),m=new THREE.MeshStandardMaterial({map,normalMap:normal});scene.add(new THREE.Mesh(new THREE.PlaneGeometry(),m));const bridge=new ReceiverBridge(scene,()=>true,4096,8,sand);assert.equal(bridge.diagnostics.available,true,bridge.diagnostics.reason);const rebuilds=bridge.diagnostics.rebuilds,atlas=bridge.diagnostics.atlasRebuilds;map.needsUpdate=true;assert.equal(bridge.sync(),true);assert.equal(bridge.diagnostics.atlasRebuilds,atlas+1);assert.equal(bridge.diagnostics.rebuilds,rebuilds);assert.equal((bridge.uniforms.receiverAlbedo.value as THREE.Texture).colorSpace,THREE.NoColorSpace);bridge.dispose();const denied=new ReceiverBridge(scene,()=>true,4096,2,sand);assert.equal(denied.diagnostics.available,false);assert.match(denied.diagnostics.reason,/layer limit/);denied.dispose();
});
