import * as THREE from 'three';
import { SkinnedReceivers } from './skinned-receivers.ts';
import type { SkinnedGPUExport } from './skinned-receivers.ts';
import { gpuSkinFragment,gpuPackFragment,gpuComposeFragment } from './gpu-skinned-receivers-glsl.ts';
const WIDTH=1024;
const vertexShader=`void main(){gl_Position=vec4(position.xy,0.,1.);}`;
/** Optional WebGL2 candidate. No normal-update readback. Final output consumes one existing water sampler. */
export class GPUSkinnedReceivers {
 readonly layout:SkinnedGPUExport;
 readonly diagnostics={available:false,reason:'not updated',updates:0,boundsEpsilon:'2 Float32 ULP relative + 0.00001m',readbackBytes:0};
 private oracle:SkinnedReceivers;private renderer:THREE.WebGLRenderer;
 private scene=new THREE.Scene();private camera=new THREE.Camera();private quad:THREE.Mesh;
 private textures:THREE.DataTexture[]=[];private targets:THREE.WebGLRenderTarget[]=[];private materials:THREE.ShaderMaterial[]=[];
 private source:THREE.DataTexture;private topology:THREE.DataTexture;private nodes:THREE.DataTexture;private bone:THREE.DataTexture;private world:THREE.DataTexture;private normal:THREE.DataTexture;private visibility:THREE.DataTexture;
 private vertices:THREE.WebGLRenderTarget;private packed:THREE.WebGLRenderTarget[];private current:THREE.WebGLRenderTarget;private output?:THREE.WebGLRenderTarget;private prefix?:THREE.DataTexture;private disposed=false;private maxDepth=0;private initialMaterial=new THREE.MeshBasicMaterial();
 constructor(renderer:THREE.WebGLRenderer,oracle:SkinnedReceivers){this.renderer=renderer;this.oracle=oracle;this.layout=oracle.exportGPU();const l=this.layout;this.maxDepth=l.nodes.reduce((d,n)=>Math.max(d,n.depth),0);
 const src=new Float32Array(l.vertices*20);for(let si=0;si<l.surfaces.length;si++){const s=l.surfaces[si];for(let vi=0;vi<s.source.length/14;vi++){const o=(s.vertexOffset+vi)*20,b=vi*14;src.set(s.source.subarray(b,b+3),o);src.set(s.source.subarray(b+3,b+6),o+4);for(let j=0;j<4;j++)src[o+8+j]=s.source[b+6+j]/16+s.boneOffset;src.set(s.source.subarray(b+10,b+14),o+12);src[o+16]=si;}}
 this.source=this.texture(src);const tri=new Float32Array(l.triangles.length*8);l.triangles.forEach((t,i)=>{tri.set([...t.vertices,t.surface,t.material],i*8);});this.topology=this.texture(tri);
 const nd=new Float32Array(l.nodes.length*8);l.nodes.forEach((n,i)=>nd.set([n.left,n.right,n.start,n.count,n.depth],i*8));this.nodes=this.texture(nd);
 this.bone=this.texture(new Float32Array(l.bones*16));this.world=this.texture(new Float32Array(l.surfaces.length*16));this.normal=this.texture(new Float32Array(l.surfaces.length*12));this.visibility=this.texture(new Float32Array(l.surfaces.length*oracle.materials.length*4));
 this.vertices=this.target(l.vertices*2);this.packed=[this.target(l.texels),this.target(l.texels)];this.current=this.packed[0];
 this.quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2),this.initialMaterial);this.quad.frustumCulled=false;this.scene.add(this.quad);
 this.materials.push(this.material(gpuSkinFragment,{sourceData:this.source,bones:this.bone,worlds:this.world,normals:this.normal,vertices:l.vertices}),this.material(gpuPackFragment,{previous:this.texture(l.staticPacked),vertexData:this.vertices.texture,triangles:this.topology,nodeData:this.nodes,visibility:this.visibility,triangleOffset:l.triangleOffset,totalTexels:l.texels,depth:0,materials:oracle.materials.length}),this.material(gpuComposeFragment,{prefixData:null,skinData:null,prefixTexels:0,skinTexels:l.texels}));
 }
 private texture(values:Float32Array){const data=new Float32Array(WIDTH*Math.max(1,Math.ceil(values.length/4/WIDTH))*4);data.set(values);const t=new THREE.DataTexture(data,WIDTH,data.length/4/WIDTH,THREE.RGBAFormat,THREE.FloatType);t.minFilter=t.magFilter=THREE.NearestFilter;t.generateMipmaps=false;t.needsUpdate=true;this.textures.push(t);return t;}
 private target(texels:number){const t=new THREE.WebGLRenderTarget(WIDTH,Math.max(1,Math.ceil(texels/WIDTH)),{type:THREE.FloatType,format:THREE.RGBAFormat,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:false,stencilBuffer:false});this.targets.push(t);return t;}
 private material(fragmentShader:string,values:Record<string,unknown>){const uniforms:Record<string,THREE.IUniform>={width:{value:WIDTH}};for(const [k,value]of Object.entries(values))uniforms[k]={value};return new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,vertexShader,fragmentShader,uniforms,depthTest:false,depthWrite:false,toneMapped:false,blending:THREE.NoBlending});}
 private upload(t:THREE.DataTexture,data:Float32Array){(t.image.data as Float32Array).set(data);t.needsUpdate=true;}
 private draw(m:THREE.ShaderMaterial,t:THREE.WebGLRenderTarget){this.quad.material=m;this.renderer.setRenderTarget(t);this.renderer.setViewport(0,0,t.width,t.height);this.renderer.setScissorTest(false);this.renderer.render(this.scene,this.camera);}
 private guard<T>(fn:()=>T):T{const r=this.renderer,target=r.getRenderTarget(),face=r.getActiveCubeFace(),level=r.getActiveMipmapLevel(),viewport=r.getViewport(new THREE.Vector4()),scissor=r.getScissor(new THREE.Vector4()),test=r.getScissorTest(),auto=r.autoClear,tone=r.toneMapping,color=r.outputColorSpace,clear=r.getClearColor(new THREE.Color()),alpha=r.getClearAlpha();try{r.autoClear=false;r.toneMapping=THREE.NoToneMapping;return fn();}finally{r.setRenderTarget(target,face,level);r.setViewport(viewport);r.setScissor(scissor);r.setScissorTest(test);r.autoClear=auto;r.toneMapping=tone;r.outputColorSpace=color;r.setClearColor(clear,alpha);}}
 update():boolean{this.diagnostics.available=false;if(this.disposed){this.diagnostics.reason='disposed';return false;}try{if(!this.renderer.extensions.has('EXT_color_buffer_float'))throw new Error('EXT_color_buffer_float required');const p=this.oracle.exportGPUPose();this.upload(this.bone,p.bones);this.upload(this.world,p.worlds);this.upload(this.normal,p.normals);const vis=this.visibility.image.data as Float32Array;for(let i=0;i<p.visible.length;i++)vis[i*4]=p.visible[i];this.visibility.needsUpdate=true;
 this.guard(()=>{this.draw(this.materials[0],this.vertices);const m=this.materials[1];m.uniforms.previous.value=this.textures[7];m.uniforms.depth.value=0;this.draw(m,this.packed[0]);this.current=this.packed[0];for(let d=this.maxDepth;d>=1;d--){const next=this.current===this.packed[0]?this.packed[1]:this.packed[0];m.uniforms.previous.value=this.current.texture;m.uniforms.depth.value=d;this.draw(m,next);this.current=next;}});this.diagnostics.available=true;this.diagnostics.reason='';this.diagnostics.updates++;return true;}catch(e){this.diagnostics.reason=String(e);return false;}}
 /** Prefix must contain whole RGBA texels; offset is texels. Returns null on invalid/stale pose. */
 compose(prefix:Float32Array):{texture:THREE.Texture;extraDataOffset:number;texels:number}|null{if(!this.diagnostics.available||this.disposed)return null;if(prefix.length%4)throw new Error('unaligned prefix');const texels=prefix.length/4,total=texels+this.layout.texels;if(!this.prefix||(this.prefix.image.data as Float32Array).length<prefix.length){this.prefix=this.texture(prefix);}else this.upload(this.prefix,prefix);if(!this.output||this.output.height!==Math.max(1,Math.ceil(total/WIDTH)))this.output=this.target(total);const m=this.materials[2];m.uniforms.prefixData.value=this.prefix;m.uniforms.skinData.value=this.current.texture;m.uniforms.prefixTexels.value=texels;this.guard(()=>this.draw(m,this.output!));return{texture:this.output.texture,extraDataOffset:texels,texels:total};}
 readback():Float32Array{if(!this.diagnostics.available)throw new Error(this.diagnostics.reason);const data=new Float32Array(this.current.width*this.current.height*4);this.guard(()=>this.renderer.readRenderTargetPixels(this.current,0,0,this.current.width,this.current.height,data));this.diagnostics.readbackBytes+=data.byteLength;return data.subarray(0,this.layout.texels*4);}
 dispose(){if(this.disposed)return;this.disposed=true;this.diagnostics.available=false;this.diagnostics.reason='disposed';this.quad.geometry.dispose();this.initialMaterial.dispose();for(const m of this.materials)m.dispose();for(const t of this.targets)t.dispose();for(const t of this.textures)t.dispose();}
}


